---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# BiodiversityCounsil

<!-- badges: start -->
<!-- badges: end -->

The goal of Biodiversity Counsel is to find out

Sea and land are treated separately

* How much is 30% and 10% according to EU
  - All natura 2.000 is in the 30%
* How much is 30% and 10% according to Biodiversity counsel (Biodiversitetsradet)
  - What has to be improved for natura 2.000 can be part of the 30%

## Potential areas

* NATURA 2000
  - Habitat types
  - How much is paragraph 3
  - how much area of different categories
  
  
## For each layer

* Total Area by habitat type (SqKm or meters)
* Proportion of Denmark
* Source
* Column 10% strictly protected EU
* Column 10% strictly protected Biodiversitetsradet
* Column 30% protected EU
* Column 30% protected Biodiversitetsradet
* Intersection (matrix NxN intersections?)

## For sea

Map of preasures for each polygon

## How interactive should we make this
